version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=chat_user
      - DB_PASSWORD=@pP8722311029
      - DB_NAME=chat_app
      - DB_PORT=3306
    volumes:
      - ./src:/usr/src/app/src
    command: npm run dev

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=@pP8722311029
      - MYSQL_DATABASE=chat_app
      - MYSQL_USER=chat_user
      - MYSQL_PASSWORD=@pP8722311029
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-data: